env:
  env_name: test

kafka:
  topic: TodoTopic
  bootstrap_servers: [localhost:9092]

url:
  is_alive_url: https://petstore.swagger.io/v2/pet/322717570?ID=1
  api_todos_url: https://localhost:44302/api/Todos

request_body:
  post: {
    'listId': 1882,
    'todoName': Monitor,
    'finishDate': !!str 2022-08-22T11:44:07.845Z
  }