env:
  env_name: test

kafka:
  topic: TodoTopic
  bootstrap_servers: [localhost:9092]

url:
  base_url: https://localhost:44302/
  route_1: status/isalive
  route_2: api/Todos
  route_3:
  route_4:

request_body:
  post: {
    'listId': 1882,
    'todoName': Monitor,
    'finishDate': !!str 2022-08-22T11:44:07.845Z
  }