env:
  env_name: test

kafka:
  topic: TodoTopic
  bootstrap_servers: [localhost:9092]

url:
  is_alive_url: https://localhost:44302/status/isalive
  api_todos_url: https://localhost:44302/api/Todos

request_body:
  post: {
    'todoId': 0,
    'listId': 1882,
    'todoName': Monitor,
    'finishDate': 2022-08-22T11:44:07.845Z
  }